### PR TITLE
Feature settings profiles

### PR DESCRIPTION
**Pull request by thenose2003**
This adds the ability to change between different settings profiles

You can also alter the names of profiles and import/export profiles

in settings gui it looks like i deleted some buttons, I just moved them to better fit the menu with the new settings profiles you can obv change it if you think its weird

### CODE REVIEW

**Comment by Soopyboo32** [comment]
image
I dont know what you are using this backup settings file/folder for, but just so you know if it is stored in the bettermap module somewhere it has a chance of being deleted. if it shouldent be deleted (eg thru version updates) it should be saved seperately in the soopyaddonsdata module

**Comment by thenose2003** [comment]
This file isn't important to the thing. I was breaking the settings file a lot so I just saved a backup to copy in. It can be removed from gitignore if you want it serves no purpose other than testing.

**Comment by Soopyboo32** [comment]
idm either way just mentioned it incase you diddnt know

**Comment by thenose2003** [comment]
alrightty

**Comment by Soopyboo32** [comment]
Can this pull request be closed cus its in #31 ?

**Pull request closed without merging**
