### PR TITLE
Add head border color customisation (thenose2003)

### PR DESCRIPTION
**Pull request by thenose2003**
It does as it says in the title

No testing has been done with YouTube or admin ranks

it saves sb level and class level too if it matters idk

Checks for class 2 secs after the 1sec until dungeon start message has been sent

Class RGBO Values
```
Archer  -  30, 170,  50, 255
Mage    -  70, 210, 210, 255
Tank    - 150, 150, 150, 255
Berserk - 255,   0,   0, 255
Healer  - 240,  70, 240, 255
```

2022-10-07_13 04 57_edited

suggested by  PridedBacon2279
https://discord.com/channels/997954712185884794/1026670727178494062/1027648437228941392

### CODE REVIEW

**Review by Soopyboo32 — CHANGES_REQUESTED** [review]
Can you add a toggle for this in the settings.

**Comment by Soopyboo32** [comment]
(maby change the border toggle setting to a dropdown and add the options be like No border, Black border, Colored border)

Also iv been thinking that border color would be a nice way to have an option to highlight yourself on the map for people used to centered map, im not sure how I would add that in but if you have any ideas it would be nice to add them aswell

**Comment by thenose2003** [comment]
- There is a setting for the border colors to select none, single color, or class color
- The setting "borderColor" was changed to "mapBorderColor"
- Colors for borders are in the config file so users can manually change them. I didn't want to put that in the menu without something to hide/unclutter the settings menu

**Review by Soopyboo32 — APPROVED** [review]
LGTM

ye im gonna start working on a better color editing gui sometime soon, so all the color stuff can be in a different menu

**Pull request merged**
