### PR TITLE
Clean up the formatting of the Cleared Room Count

### PR DESCRIPTION
**Pull request by DylanBruner**

### CODE REVIEW

**Comment by DylanBruner** [comment]
image

**Comment by Soopyboo32** [comment]
i wonder if its worth it to use bold spaces to make it line up exactly
(bold = +1px width to any character including spaces)

**Comment by DylanBruner** [comment]
I will take a look at it when I get home and open a new PR if it works

**Comment by Soopyboo32** [comment]
preferably add the changes to this request instead of making a new one

**Comment by DylanBruner** [comment]
Once I find out how to do that I will, first PR 😅

**Comment by DylanBruner** [comment]
I tried with bold characters and was unable to get it working. If someone has any ideas I'll give it a shot.

**Pull request closed without merging**
